[package]
name = "tokio-api-key-server"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "keys"
path = "src/main.rs"

[dependencies]
rand = "0.6.5"
ureq = "0.10.0"